import { Product, Category, Order, Review, Notification } from '../types';

export const categories: Category[] = [
  {
    id: 'cat-1',
    name: 'Cakes',
    description: 'Delicious cakes for every occasion',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'cat-2',
    name: 'Pastries',
    description: 'Fresh baked pastries daily',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'cat-3',
    name: 'Bread',
    description: 'Artisan bread made with love',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'cat-4',
    name: 'Cookies',
    description: 'Crispy and chewy cookies',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'cat-5',
    name: 'Cupcakes',
    description: 'Cute and delicious cupcakes',
    createdAt: '2024-01-15T10:00:00Z',
  },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Chocolate Dream Cake',
    description: 'Rich chocolate cake with smooth ganache frosting. Perfect for celebrations.',
    price: 45.99,
    categoryId: 'cat-1',
    categoryName: 'Cakes',
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaG9jb2xhdGUlMjBjYWtlfGVufDF8fHx8MTc2MjA0MTU0NHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    stock: 8,
    rating: 4.8,
    reviewCount: 24,
    createdAt: '2024-10-01T10:00:00Z',
  },
  {
    id: 'prod-2',
    name: 'Butter Croissants',
    description: 'Flaky, buttery croissants baked fresh every morning. Pack of 6.',
    price: 12.99,
    categoryId: 'cat-2',
    categoryName: 'Pastries',
    image: 'https://images.unsplash.com/photo-1648279549817-51d7fbdf3dff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9pc3NhbnRzJTIwYmFrZXJ5fGVufDF8fHx8MTc2MjA5Nzk5OHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    stock: 15,
    rating: 4.9,
    reviewCount: 42,
    createdAt: '2024-10-05T10:00:00Z',
  },
  {
    id: 'prod-3',
    name: 'Artisan Sourdough Loaf',
    description: 'Traditional sourdough with a crispy crust and soft interior.',
    price: 8.99,
    categoryId: 'cat-3',
    categoryName: 'Bread',
    image: 'https://images.unsplash.com/photo-1534620808146-d33bb39128b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcnRpc2FuJTIwYnJlYWR8ZW58MXx8fHwxNzYyMDM2NjI0fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    stock: 20,
    rating: 4.7,
    reviewCount: 31,
    createdAt: '2024-10-08T10:00:00Z',
  },
  {
    id: 'prod-4',
    name: 'Chocolate Chip Cookies',
    description: 'Classic cookies loaded with chocolate chips. Pack of 12.',
    price: 9.99,
    categoryId: 'cat-4',
    categoryName: 'Cookies',
    image: 'https://images.unsplash.com/photo-1702743117135-9207ef2e366a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb29raWVzJTIwYmFrZWR8ZW58MXx8fHwxNzYyMDk3OTk5fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    stock: 25,
    rating: 4.6,
    reviewCount: 18,
    createdAt: '2024-10-10T10:00:00Z',
  },
  {
    id: 'prod-5',
    name: 'Vanilla Cupcakes',
    description: 'Light vanilla cupcakes with buttercream frosting. Pack of 6.',
    price: 15.99,
    categoryId: 'cat-5',
    categoryName: 'Cupcakes',
    image: 'https://images.unsplash.com/photo-1690584177253-58e128f05ceb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjdXBjYWtlcyUyMGRlc3NlcnR8ZW58MXx8fHwxNzYyMDE1MTg2fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    stock: 12,
    rating: 4.5,
    reviewCount: 15,
    createdAt: '2024-10-12T10:00:00Z',
  },
  {
    id: 'prod-6',
    name: 'Mixed Pastry Box',
    description: 'Assorted pastries including danishes, turnovers, and eclairs.',
    price: 18.99,
    categoryId: 'cat-2',
    categoryName: 'Pastries',
    image: 'https://images.unsplash.com/photo-1696721497670-d57754966c1e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWtlcnklMjBwYXN0cmllc3xlbnwxfHx8fDE3NjIwMDQ4MjJ8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    stock: 10,
    rating: 4.8,
    reviewCount: 28,
    createdAt: '2024-10-15T10:00:00Z',
  },
  {
    id: 'prod-7',
    name: 'Whole Wheat Bread',
    description: 'Healthy whole wheat bread, perfect for sandwiches.',
    price: 6.99,
    categoryId: 'cat-3',
    categoryName: 'Bread',
    image: 'https://images.unsplash.com/photo-1663904460424-91895028aa9e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmVzaCUyMGJyZWFkJTIwbG9hdmVzfGVufDF8fHx8MTc2MjA5Nzk5N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    stock: 18,
    rating: 4.4,
    reviewCount: 22,
    createdAt: '2024-10-18T10:00:00Z',
  },
  {
    id: 'prod-8',
    name: 'Red Velvet Cake',
    description: 'Classic red velvet cake with cream cheese frosting.',
    price: 42.99,
    categoryId: 'cat-1',
    categoryName: 'Cakes',
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaG9jb2xhdGUlMjBjYWtlfGVufDF8fHx8MTc2MjA0MTU0NHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    stock: 6,
    rating: 4.9,
    reviewCount: 35,
    createdAt: '2024-10-20T10:00:00Z',
  },
];

export const reviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    userId: 'user-2',
    userName: 'Sarah Johnson',
    rating: 5,
    comment: 'Absolutely delicious! The chocolate ganache was perfect.',
    createdAt: '2024-10-25T14:30:00Z',
  },
  {
    id: 'rev-2',
    productId: 'prod-1',
    userId: 'user-3',
    userName: 'Mike Chen',
    rating: 4,
    comment: 'Great cake, very moist. Would buy again.',
    createdAt: '2024-10-22T10:15:00Z',
  },
  {
    id: 'rev-3',
    productId: 'prod-2',
    userId: 'user-2',
    userName: 'Sarah Johnson',
    rating: 5,
    comment: 'Best croissants in town! So flaky and buttery.',
    createdAt: '2024-10-28T08:45:00Z',
  },
];

export const orders: Order[] = [
  {
    id: 'order-1',
    userId: 'user-2',
    userName: 'Sarah Johnson',
    userEmail: 'sarah@example.com',
    items: [
      {
        productId: 'prod-1',
        productName: 'Chocolate Dream Cake',
        price: 45.99,
        quantity: 1,
      },
      {
        productId: 'prod-2',
        productName: 'Butter Croissants',
        price: 12.99,
        quantity: 2,
      },
    ],
    total: 71.97,
    status: 'delivered',
    shippingAddress: {
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
    },
    createdAt: '2024-10-20T10:00:00Z',
    updatedAt: '2024-10-25T15:30:00Z',
  },
  {
    id: 'order-2',
    userId: 'user-2',
    userName: 'Sarah Johnson',
    userEmail: 'sarah@example.com',
    items: [
      {
        productId: 'prod-3',
        productName: 'Artisan Sourdough Loaf',
        price: 8.99,
        quantity: 2,
      },
    ],
    total: 17.98,
    status: 'shipped',
    shippingAddress: {
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
    },
    createdAt: '2024-10-28T09:00:00Z',
    updatedAt: '2024-10-30T14:20:00Z',
  },
  {
    id: 'order-3',
    userId: 'user-3',
    userName: 'Mike Chen',
    userEmail: 'mike@example.com',
    items: [
      {
        productId: 'prod-4',
        productName: 'Chocolate Chip Cookies',
        price: 9.99,
        quantity: 3,
      },
      {
        productId: 'prod-5',
        productName: 'Vanilla Cupcakes',
        price: 15.99,
        quantity: 1,
      },
    ],
    total: 45.96,
    status: 'processing',
    shippingAddress: {
      street: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90001',
      country: 'USA',
    },
    createdAt: '2024-10-30T11:30:00Z',
    updatedAt: '2024-10-31T08:15:00Z',
  },
  {
    id: 'order-4',
    userId: 'user-4',
    userName: 'Emma Wilson',
    userEmail: 'emma@example.com',
    items: [
      {
        productId: 'prod-8',
        productName: 'Red Velvet Cake',
        price: 42.99,
        quantity: 1,
      },
    ],
    total: 42.99,
    status: 'pending',
    shippingAddress: {
      street: '789 Pine Rd',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      country: 'USA',
    },
    createdAt: '2024-11-01T16:45:00Z',
    updatedAt: '2024-11-01T16:45:00Z',
  },
];

export const notifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-2',
    title: 'Order Delivered',
    message: 'Your order #order-1 has been delivered successfully!',
    type: 'order',
    read: true,
    createdAt: '2024-10-25T15:30:00Z',
  },
  {
    id: 'notif-2',
    userId: 'user-2',
    title: 'Order Shipped',
    message: 'Your order #order-2 is on its way!',
    type: 'order',
    read: false,
    createdAt: '2024-10-30T14:20:00Z',
  },
  {
    id: 'notif-3',
    userId: 'user-2',
    title: 'Special Offer',
    message: 'Get 20% off on all cakes this weekend!',
    type: 'promo',
    read: false,
    createdAt: '2024-11-01T09:00:00Z',
  },
];
